import { Activity } from "./types";

export const activities: Activity[] = [
  {
    id: "event-gardens-1",
    title: "Gardens by the Bay Children's Weekend Trail",
    category: "Outdoor nature",
    description: "Light nature trail and kid-focused discovery stations.",
    indoorOutdoor: "outdoor",
    energyLevel: "low",
    ageMin: 4,
    ageMax: 10,
    durationHours: 2,
    estimatedCostSgd: 20,
    weatherSensitive: true,
    timings: ["morning", "afternoon"],
    area: "Marina Bay",
    travelMinutesFromHome: 25,
    isEvent: true,
    sourceUrl: "https://www.gardensbythebay.com.sg"
  },
  {
    id: "evergreen-condo-pool",
    title: "Relaxing family pool time at condo",
    category: "Water play/swimming",
    description: "Low-stress unstructured play with breaks and snacks.",
    indoorOutdoor: "outdoor",
    energyLevel: "low",
    ageMin: 2,
    ageMax: 12,
    durationHours: 2,
    estimatedCostSgd: 0,
    weatherSensitive: true,
    timings: ["morning", "afternoon"],
    area: "Home",
    travelMinutesFromHome: 5,
    isEvent: false,
    sourceUrl: "https://www.healthhub.sg"
  },
  {
    id: "event-kidzania",
    title: "KidZania Singapore 2-hour roleplay slot",
    category: "Indoor play",
    description: "Structured roleplay activities for young kids.",
    indoorOutdoor: "indoor",
    energyLevel: "medium",
    ageMin: 4,
    ageMax: 12,
    durationHours: 2,
    estimatedCostSgd: 55,
    weatherSensitive: false,
    timings: ["morning", "afternoon"],
    area: "Sentosa",
    travelMinutesFromHome: 35,
    isEvent: true,
    sourceUrl: "https://www.kidzania.com"
  },
  {
    id: "evergreen-jacob-ball", 
    title: "Jacob Ballas Children's Garden",
    category: "Outdoor nature",
    description: "Nature-themed play with water and sand zones.",
    indoorOutdoor: "outdoor",
    energyLevel: "medium",
    ageMin: 3,
    ageMax: 10,
    durationHours: 2.5,
    estimatedCostSgd: 0,
    weatherSensitive: true,
    timings: ["morning", "afternoon"],
    area: "Bukit Timah",
    travelMinutesFromHome: 30,
    isEvent: false,
    sourceUrl: "https://www.nparks.gov.sg"
  },
  {
    id: "evergreen-science-centre",
    title: "Science Centre KidsSTOP",
    category: "Learning/creative",
    description: "Interactive exhibits for young children.",
    indoorOutdoor: "indoor",
    energyLevel: "medium",
    ageMin: 3,
    ageMax: 8,
    durationHours: 2,
    estimatedCostSgd: 35,
    weatherSensitive: false,
    timings: ["morning", "afternoon"],
    area: "Jurong East",
    travelMinutesFromHome: 40,
    isEvent: false,
    sourceUrl: "https://www.science.edu.sg"
  },
  {
    id: "evergreen-sungei-buloh",
    title: "Sungei Buloh easy boardwalk nature walk",
    category: "Animals/wildlife",
    description: "Slow-paced boardwalk route ideal for relaxed family walks.",
    indoorOutdoor: "outdoor",
    energyLevel: "low",
    ageMin: 5,
    ageMax: 12,
    durationHours: 2,
    estimatedCostSgd: 0,
    weatherSensitive: true,
    timings: ["morning"],
    area: "Kranji",
    travelMinutesFromHome: 45,
    isEvent: false,
    sourceUrl: "https://www.nparks.gov.sg"
  }
];
